/*
 * This file is generated by jOOQ.
*/
package com.gasteva.jooqGen;


import com.gasteva.jooqGen.tables.Twitts;
import com.gasteva.jooqGen.tables.Users;
import com.gasteva.jooqGen.tables.records.TwittsRecord;
import com.gasteva.jooqGen.tables.records.UsersRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>litteltwitter</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<TwittsRecord, Integer> IDENTITY_TWITTS = Identities0.IDENTITY_TWITTS;
    public static final Identity<UsersRecord, Integer> IDENTITY_USERS = Identities0.IDENTITY_USERS;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<TwittsRecord> KEY_TWITTS_PRIMARY = UniqueKeys0.KEY_TWITTS_PRIMARY;
    public static final UniqueKey<UsersRecord> KEY_USERS_PRIMARY = UniqueKeys0.KEY_USERS_PRIMARY;
    public static final UniqueKey<UsersRecord> KEY_USERS_NIKNAME_UNIQUE = UniqueKeys0.KEY_USERS_NIKNAME_UNIQUE;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<TwittsRecord, UsersRecord> FK_USER_ID = ForeignKeys0.FK_USER_ID;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<TwittsRecord, Integer> IDENTITY_TWITTS = createIdentity(Twitts.TWITTS, Twitts.TWITTS.ID);
        public static Identity<UsersRecord, Integer> IDENTITY_USERS = createIdentity(Users.USERS, Users.USERS.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<TwittsRecord> KEY_TWITTS_PRIMARY = createUniqueKey(Twitts.TWITTS, "KEY_twitts_PRIMARY", Twitts.TWITTS.ID);
        public static final UniqueKey<UsersRecord> KEY_USERS_PRIMARY = createUniqueKey(Users.USERS, "KEY_users_PRIMARY", Users.USERS.ID);
        public static final UniqueKey<UsersRecord> KEY_USERS_NIKNAME_UNIQUE = createUniqueKey(Users.USERS, "KEY_users_NikName_UNIQUE", Users.USERS.NIKNAME);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<TwittsRecord, UsersRecord> FK_USER_ID = createForeignKey(com.gasteva.jooqGen.Keys.KEY_USERS_PRIMARY, Twitts.TWITTS, "FK_User_ID", Twitts.TWITTS.USERID);
    }
}
