/*
 * This file is generated by jOOQ.
*/
package com.gasteva.jooqGen;


import com.gasteva.jooqGen.tables.Following;
import com.gasteva.jooqGen.tables.Twitts;
import com.gasteva.jooqGen.tables.Users;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in litteltwitter
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>litteltwitter.following</code>.
     */
    public static final Following FOLLOWING = com.gasteva.jooqGen.tables.Following.FOLLOWING;

    /**
     * The table <code>litteltwitter.twitts</code>.
     */
    public static final Twitts TWITTS = com.gasteva.jooqGen.tables.Twitts.TWITTS;

    /**
     * The table <code>litteltwitter.users</code>.
     */
    public static final Users USERS = com.gasteva.jooqGen.tables.Users.USERS;
}
